---
- name: Find user UID
  command: id -u {{ ansible_env.USER }}
  register: user_uid
  changed_when: false

- name: "Get the PID of {{ user_graphical_process_name }} for the user {{ ansible_env.USER }}"
  shell: pgrep -u {{ ansible_env.USER }} -a {{ user_graphical_process_name }} | head -n 1 | awk '{print $1}'
  register: user_graphical_process_name_pid
  changed_when: false

- name: Get environment variables for the user_graphical_process_name process
  command: cat /proc/{{ user_graphical_process_name_pid.stdout }}/environ
  register: user_graphical_process_name_environ
  changed_when: false

- name: Convert environ string to a dictionary using Jinja2 template
  set_fact:
    active_user_environ_dict: "{{ lookup('template', 'parse_environ.j2') | from_json }}"
  vars:
    environ_string: "{{ user_graphical_process_name_environ.stdout }}"