
- name: Ensure that the efi partition is mounted
  include_role:
    name: arch_chroot_esp_mount

- name: Check if vmlinuz-linux exists
  stat:
    path: "{{ arch_chroot_esp_mount_path }}/vmlinuz-linux"
  register: vmlinuz


- name: Install grub
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} grub-install --target=x86_64-efi --bootloader-id=grub_korbad --efi-directory=/boot
  become: true
  notify: regenerate initramfs image

- name: Configure GRUB defaults
  template:
    src: grub.j2
    dest: "{{ arch_chroot_mount_path }}/etc/default/grub"
  vars:
    grub_default: '0'
    grub_timeout: '5'
    grub_distributor: 'Arch'
    grub_cmdline_linux_default: 'quiet'
    grub_cmdline_linux: ''
    grub_disable_os_prober: true
  become: true
  notify: regenerate initramfs image

- name: Get UUID of the root partition
  command:
    cmd: blkid -s UUID -o value /dev/disk/by-id/{{ disk_by_id }}-part{{ root_partition_number }}
  become: true
  register: root_uuid

- name: Configure custom GRUB entries
  template:
    src: 40_custom.j2
    dest: "{{ arch_chroot_mount_path }}/etc/grub.d/40_custom"
    mode: '0755'
  vars:
    custom_boot_entries:
      - name: "korbad - disk {{ disk_by_id }}"
        uuid: "{{ root_uuid.stdout }}"
  become: true
  notify: regenerate initramfs image

- name: Generate GRUB configuration file
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} grub-mkconfig -o /boot/grub/grub.cfg
  become: true
  notify: regenerate initramfs image
