---
- name: Create korbad partition
  community.general.parted:
    device: "{{ arch_disk_device_path_by_id }}"
    number: "{{ korbad_partition_number }}"
    state: present
    resize: true
    part_start: 100GiB
    part_end: 130GiB
    fs_type: ext4
    name: korbad
    label: gpt
  become: true
  register: korbad_part

- name: Inform the OS of partition table changes
  command: partprobe {{ arch_disk_device_path_by_id }}
  become: true

- name: Trigger udev rules
  command: udevadm trigger
  become: true

- name: Format korbad partition
  community.general.filesystem:
    force: true
    dev: "{{ arch_disk_device_path_by_id }}-part{{ korbad_partition_number }}"
    fstype: ext4
  become: true
