- name: Create swap partition
  community.general.parted:
    device: "{{ arch_disk_device_path_by_id }}"
    number: "{{ swap_partition_number }}"
    state: present
    part_start: 30GiB
    part_end: 40GiB
    label: gpt
    name: swap
  become: true

- name: Inform the OS of partition table changes
  command: partprobe {{ arch_disk_device_path_by_id }}
  become: true

- name: Format swap partition
  community.general.filesystem:
    dev: "{{ arch_disk_device_path_by_id }}-part{{ swap_partition_number }}"
    fstype: swap
  become: true
