- name: Ensure that the nss-mdns package is installed in chroot
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} pacman -S --noconfirm nss-mdns
  become: true

- name: Set static line in /etc/nsswitch.conf in chroot
  ansible.builtin.lineinfile:
    path: "{{ arch_chroot_mount_path }}/etc/nsswitch.conf"
    regexp: '^hosts:.*$'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
  become: true

