---
- name: Create EFI partition
  community.general.parted:
    device: "{{ device }}"
    number: "{{ boot_partition_number }}"
    flags: [boot, esp]
    state: present
    part_end: 250MiB
    name: ESP
    label: gpt

- name: Format EFI partition
  become: true
  filesystem:
    fstype: vfat
    dev: "{{ device }}{{ boot_partition_number }}"

- name: Create /boot/efi mountpoint
  file:
    state: directory
    name: /boot/efi
    recurse: yes

- name: Mount the ESP
  mount:
    state: mounted
    src: "{{ device }}{{ boot_partition_number }}"
    path: /boot/efi
    fstype: vfat
