---
- name: Remove all paritions
  include_tasks: remove_all.yml

- name: Set up boot partition
  include_tasks: boot.yml

- name: Set up primary partition
  include_tasks: primary.yml

- name: Set up home partition
  include_tasks: home.yml