---
- name: Create primary partition
  community.general.parted:
    device: "{{ device }}"
    number: "{{ primary_partition_number }}"
    state: present
    part_start: 8GiB
    part_end: 30GiB
    fs_type: ext4
    name: root
    label: gpt
  register: primary_part

- name: Format primary partition
  community.general.filesystem:
    dev: "{{ device }}"
    fstype: ext4

- name: Mount primary partition
  mount:
    path: /
    state: mounted
    fstype: ext4
    src: "{{ device }}{{ primary_partition_number }}"
