---
- name: "Read partition information for device {{ device }}"
  community.general.parted:
    device: "{{ device }}"
    unit: GiB
  register: sdb_info

- name: "Unmount drive {{ device }}{{ item.num }}"
  mount:
    path: "{{ device }}{{ item.num }}"
    state: absent
  loop: '{{ sdb_info.partitions }}'

# - name: Unmount drive
#   command:
#     cmd: "parted ---pretend-input-tty {{ device }} resizepart {{ item.num }} yes 100%"
#   loop: '{{ sdb_info.partitions }}'


- name: Unmount partitions
  command: "umount {{ device }}{{ item.num }}"
  loop: '{{ sdb_info.partitions }}'
  failed_when: false

- name: "Remove all partitions from disk {{ device }}"
  community.general.parted:
    device: "{{ device }}"
    number: '{{ item.num }}'
    state: absent
    label: gpt
    resize: yes
  loop: '{{ sdb_info.partitions }}'
