---
- name: Ensure /etc directory exists in chroot
  file:
    path: "{{ arch_chroot_mount_path }}/etc"
    state: directory
    mode: '0755'
  become: true

- name: Generate filesystem table (fstab) for arch chroot at {{ arch_chroot_mount_path }}
  template:
    src: fstab.j2
    dest: "{{ arch_chroot_mount_path }}/etc/fstab"
    mode: '0644'
  become: true
  vars:
    fstab_entries:
      - device: /dev/disk/by-id/{{ disk_by_id }}-part{{ boot_partition_number }}
        mount_point: /boot
        type: vfat
        options: defaults
        dump: 0
        pass: 2
      - device: /dev/disk/by-id/{{ disk_by_id }}-part{{ root_partition_number }}
        mount_point: /
        type: ext4
        options: defaults
        dump: 0
        pass: 1