---
# https://wiki.archlinux.org/title/systemd-boot
- name: Install systemd-boot to ESP
  command:
    cmd: "bootctl install"
  become: true

- name: Ensure systemd-boot config file is managed
  template:
    src: loader.conf.j2
    dest: "{{ esp_mount_path }}/loader/loader.conf"
    owner: root
    group: root
    mode: '0644'
  become: true

- include_tasks: custom_boot_entries.yml