---
- name: Create swap partition
  community.general.parted:
    device: "{{ device }}"
    number: 1
    flags: [ "swap" ]
    state: present
    fs_type: swap
- name: Create boot partition
  community.general.parted:
    device: "{{ device }}"
    number: 2
    start: 1GB
    end: 500MB
    flags: [ "boot" ]
    state: present
    fs_type: ext2
- name: Create primary partition
  community.general.parted:
    device: "{{ device }}"
    number: 3
    start: 500MB
    end: 100%
    flags: [ "primary" ]
    state: present
    fs_type: ext4