- name: Create a temporary directory for the partition mount point
  ansible.builtin.tempfile:
    state: directory
  register: temp_mounted_partition_path

- name: Mount the partition
  ansible.builtin.mount:
    path: "{{ temp_mounted_partition_path.path }}"
    src: "{{ disk_device_path_by_id }}-part{{ partition_number }}"
    fstype: auto
    state: ephemeral
  become: true
  vars:
    disk_device_path_by_id: "/dev/disk/by-id/{{ disk_by_id }}"

- name: Generate device_dict fact
  include_role:
    name: device_dict