
- name: Ensure disk is set up with Arch installation
  include_tasks: partitions_and_filesystems.yml
  vars:
    arch_disk_device_path_by_id: "/dev/disk/by-id/{{ arch_disk_by_id }}"
    boot_partition_number: 1
    root_partition_number: 2
    korbad_partition_number: 3
    data_partition_number: 4