# Handler: Regenerate Initramfs Image in Arch Linux
# Purpose: Uses `mkinitcpio` within a chroot environment, targeting a mount path specified by `arch_chroot_mount_path`.
#
# Scenarios to Use:
# 1. Kernel Update - Ensures compatibility with new kernels.
# 2. Module Changes - Incorporates system module changes or new hooks.
# 3. New Drivers - Adds drivers required early in the boot process.
# 4. Config Changes - Adjusts for configurations related to early boot (e.g., LUKS, LVM, RAID).
# 5. Chroot - Allows modifications from an external environment (e.g., live boot).
# 6. Automated Setups - Assures up-to-date initramfs in automated Arch setups (e.g., custom distros, PXE boot).

- name: regenerate initramfs image
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} mkinitcpio -P
  become: true
