- name: Check for open files using lsof
  ansible.builtin.command:
    cmd: lsof {{ disk_mount_point }}
  become: true
  register: open_files
  failed_when: false

- debug:
    var: open_files.stdout_lines