- name: Refresh device dict
  include_tasks: refresh_device_dict.yml

- name: "Unmount disk mount points"
  include_tasks: fuser_kill_processes.yml
  loop: '{{ mount_points_for_disk_to_unmount }}'
  loop_control:
    loop_var: disk_mount_point
  vars:
    mount_points_for_disk_to_unmount: "{{ device_dict[disk_id_to_unmount].partitions.values() | map(attribute='mounts') | list | flatten }}"
  when: disk_id_to_unmount in device_dict

- name: Refresh device dict
  include_tasks: refresh_device_dict.yml

- name: "Unmount disk mount points"
  include_tasks: unmount_disk_mount_point.yml
  loop: '{{ mount_points_for_disk_to_unmount }}'
  loop_control:
    loop_var: disk_mount_point
  vars:
    mount_points_for_disk_to_unmount: "{{ device_dict[disk_id_to_unmount].partitions.values() | map(attribute='mounts') | list | flatten }}"
  when: disk_id_to_unmount in device_dict

- name: Sync filesystems after unmounting
  command:
    cmd: sync
  become: true
