- name: "Unmount disk mount point {{ disk_mount_point }}"
  command:
    cmd: umount --recursive {{ disk_mount_point }}
  become: true
  failed_when: false

- name: Refresh device dict
  include_tasks: refresh_device_dict.yml

- name: Ensure filesystem write buffering is complete
  command:
    cmd: sync
  become: true